# Generated by Django 2.2.12 on 2020-05-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Dia_chi',
            field=models.TextField(blank=True, verbose_name='Địa chỉ'),
        ),
    ]
