# Generated by Django 2.2.12 on 2020-05-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20200504_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Dia_chi',
            field=models.CharField(blank=True, max_length=500, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='Ghi_chu',
            field=models.CharField(max_length=500, verbose_name='Ghi Chú'),
        ),
    ]
